language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  api_key:
    secure: kOnBF/TEzCLn/Ef1DOROJwVrOtiGj49rwrtBWpweGpK70OZJyAe0nh+oPHeOtRjs05k0jeBB013I4u2tPppAFMwZjmK08DUM/Sy9gLAKhGHvAaH7Fzlnl4bcBiCSVz/YzRT2uHDDi3vVv2UFRn3waF67YMCExXt6JKOgOS7DmOmytmvzFbBZdZfcClPzwVBAXu0mTB9nEMawi9QsHp4ZjOJ3hFFrBQHXpbIT+IwLCCYtEAOLyl4Uk5jnITkTVXnACyd3/JEFhnSDX/zofbAgkMkLYTPcNNKmWCyCrYzWPJSNIi2wuIVyxJ5IcBFt3k0nuRkZYdMWr2WFyLpREh6rD3/GX82ULmehVn62s7mhvNeQpBl8WXFu+Bjy9r3l3wF2F0i8ZGgOFlJvoEHQB66DsFhlbD9rbwLoyo4gq3fxDcq7cCPf0IE2b7K1YmVnPWqLfmmPhD1eOIE1BT9VhLQ7ZO6+iBT/FzoT9CWB+0SeGgGlnJQE8I3u23txRsVXnfCrbQ6pLGYYlZCakKlgM6LaUNEPy4cp+3B2enf/aDF1JpUE99yegd1WZr+3cyIwE7QUHBWyE4pOmqxy4he+x2MeJO80IgX7KJFhTs/Xqz2pT5r5D+4c5xI9lOTQUTaWEvToFPerjlXRGDLUAB9xylQXUGlMw8sgjRrUm6yc+uZA9uU=
  on:
    tags: true
    repo: chinjs/chin
    branch: publish
