language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  api_key:
    secure: cnldg0rDkQ6VBiGai8MSQk4O5VmPVUM52gHJLrG/PMEGvKCuG2JywtDI7mNVnB6+OS+5EWemxqihTDcG/Rqdm1eWwIYIUTI+jTRyRuWKCX9aPqVyL3sL9j/hXflAv2JuERLHWYYtnoge4FwvFC7DeKc3H2eUdwB9bDmhRu04hVyuKMwgd2Id1ULh5jH4/9GT2bra6SlYDM4lnyQa0PvPFm4iHZMqPP8VUvp3wGKhCswoCY3CisIc2cUESE7PHNuefbNZ/M2cSqU3oRe9b+EYRFrwugNCf3xJ2TFPsEO52piL7B7mbUns6KJxA2+Arisg/NPFlf+NgPX5TEYLVs2VTkVi7U5cPehwPp2T0dslCitgYwXzrAkV/7sl0J2JMbCc4qXiPIA6uDyhC7amcqddAwgGN1zkqsiRYksmiQQzNBurhvS0/lcdOPpc/RDlIXXYAX2jRLTmimtI2SmPHfl4F1h0Fxr1+RfLNxsXw3hvCQNWjakDHH2AcZg1N4yN9jLR3bwd0qEm166geSPra+uHkwEgJ6K/YZM2FJcWV/wkE2zurCNUeuQk+mPJnXOLEUqT/uhK7AK51E3Ff9OTn5ktYE+gDkh0816T+A+l7BdaKAF6/NhDcLDrADzUSGGqJ/W3RlMN+6o+wUXrw+BFyAaLfKkkB8vUBrVbaw1sKN9ePe4=
  on:
    tags: true
    repo: chinjs/chin
    branch: publish
