// flow-typed signature: f775be433666ee334385e43a373d2389
// flow-typed version: <<STUB>>/es6-micro-loader_v^0.2.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-micro-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-micro-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es6-micro-loader/dist/system-polyfill' {
  declare module.exports: any;
}

declare module 'es6-micro-loader/dist/system-polyfill.min' {
  declare module.exports: any;
}

declare module 'es6-micro-loader/server' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es6-micro-loader/dist/system-polyfill.js' {
  declare module.exports: $Exports<'es6-micro-loader/dist/system-polyfill'>;
}
declare module 'es6-micro-loader/dist/system-polyfill.min.js' {
  declare module.exports: $Exports<'es6-micro-loader/dist/system-polyfill.min'>;
}
declare module 'es6-micro-loader/index' {
  declare module.exports: $Exports<'es6-micro-loader'>;
}
declare module 'es6-micro-loader/index.js' {
  declare module.exports: $Exports<'es6-micro-loader'>;
}
declare module 'es6-micro-loader/server.js' {
  declare module.exports: $Exports<'es6-micro-loader/server'>;
}
