// flow-typed signature: 68b4eb2404e9fea666f8c642f60c1a8d
// flow-typed version: <<STUB>>/figures_v2.0.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'figures'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'figures' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'figures/index' {
  declare module.exports: $Exports<'figures'>;
}
declare module 'figures/index.js' {
  declare module.exports: $Exports<'figures'>;
}
